[package]
name = "customer_support_system"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["full"]}
axum = {version = "0.8"}
sea-orm = { version = "1.1.13", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}
dotenvy = "0.15.7"