//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::users::Entity as UserEntity;
pub use super::customers::Entity as CustomerEntity;
pub use super::tickets::Entity as TicketEntity;
pub use super::communications::Entity as CommunicationEntity;
pub use super::knowledge_base::Entity as KBEntity;
pub use super::tags::Entity as TagEntity;
pub use super::analytics::Entity as AnalyticsEntity;
pub use super::audit_logs::Entity as AuditLogEntity;



